// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EfSqlAe.Models;

public partial class Employees
{
    public int EmployeeID { get; set; }

    public string SSN { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public decimal Salary { get; set; }
}